version: "3.9"

services:
  db:
    container_name: database
    command: --init-file /data/application/init.sql
    image: mysql
    restart: always
    env_file:
      - database_config/mysql.env
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./database_config/init.sql:/data/application/init.sql
  web:
    container_name: server
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  db:
    driver: local