version: "3.3"

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django_gunicorn
  db:
    container_name: database
    command: --init-file /data/application/init.sql
    image: mysql
    restart: always
    env_file:
      - database_config/mysql.env
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
      - ./database_config/init.sql:/data/application/init.sql
  web:
    container_name: server
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
volumes:
  static:
  db:
    driver: local