# Generated by Django 4.0.4 on 2022-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name': 'Engineer',
                'verbose_name_plural': 'Engineers',
            },
        ),
    ]
